# Generated by Django 3.2.13 on 2022-07-02 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OJ', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='previous_submission',
            field=models.TextField(blank=True, null=True),
        ),
    ]
