# Generated by Django 3.2.13 on 2022-07-02 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OJ', '0002_submissions_previous_submission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-score']},
        ),
    ]
